comment: false

coverage:
  status:
    project:
      default:
        # Commits pushed to master should not make the overall
        # project coverage decrease by more than 1%:
        target: auto
        threshold: 1%
    patch:
      default:
        # Be tolerant on slight code coverage diff on PRs to limit
        # noisy red coverage status on github PRs.
        # Note The coverage stats are still uploaded
        # to codecov so that PR reviewers can see uncovered lines
        # in the github diff if they install the codecov browser
        # extension:
        # https://github.com/codecov/browser-extension
        target: auto
        threshold: 1%
 
fixes:
  # reduces pip-installed path to git root and
  # remove dist-name from setup-installed path
  - "*/python2.7/site-packages/::py2.7/"
  - "*/python3.7/site-packages/::py3.7/"
  - "*/python3.8/site-packages/::py3.8/"
  - "*/python3.9/site-packages/::py3.9/"
  - "*/python3.10/site-packages/::py3.10/"
  - "*/python3.11/site-packages/::py3.11/"
  - "*/python3.12/site-packages/::py3.12/"
  - "*/pypy2.7-*/site-packages/::pypy2.7/"
  - "*/pypy3.7-*/site-packages/::pypy3.7/"
  - "*/pypy3.8-*/site-packages/::pypy3.8/"
  - "*/pypy3.9-*/site-packages/::pypy3.9/"
  - "*/pypy3.10-*/site-packages/::pypy3.10/"
  - "*/python2.7/site-packages/multiprocess-*::py2.7/"
  - "*/python3.7/site-packages/multiprocess-*::py3.7/"
  - "*/python3.8/site-packages/multiprocess-*::py3.8/"
  - "*/python3.9/site-packages/multiprocess-*::py3.9/"
  - "*/python3.10/site-packages/multiprocess-*::py3.10/"
  - "*/python3.11/site-packages/multiprocess-*::py3.11/"
  - "*/python3.12/site-packages/multiprocess-*::py3.12/"
  - "*/pypy2.7-*/site-packages/multiprocess-*::pypy2.7/"
  - "*/pypy3.7-*/site-packages/multiprocess-*::pypy3.7/"
  - "*/pypy3.8-*/site-packages/multiprocess-*::pypy3.8/"
  - "*/pypy3.9-*/site-packages/multiprocess-*::pypy3.9/"
  - "*/pypy3.10-*/site-packages/multiprocess-*::pypy3.10/"
